version: '3.8'

services:
  autonomopro:
    image: marcos/autonomopro:latest
    ports:
      - "8080:8080"
    networks:
      - bridge_network
    depends_on:
    - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_USER=autonomopro
      - MYSQL_ROOT_PASSWORD=autonomopro
      - MYSQL_PASSWORD=autonomopro
    networks:
      - bridge_network
  
  maven:
    build:
      context: .
      dockerfile: Dockerfilemaven
    depends_on:
      - mysql
    networks:
      - bridge_network


networks:
  bridge_network:
    driver: bridge